version: '3'
services:
    express:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DSN=mongodb://mongodb:27017/employees
            - DSN_TEST=mongodb://mongodb:27017/test
        volumes:
            - ./:/app/
            - /app/node_modules/
        ports:
            - 1337:1337
        links:
            - mongodb
        command: "npm run prod"

    mongodb:
        image: mongo
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod